import React, { createContext, useContext, useState, useCallback } from "react";

type Language = "en" | "ur";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<string, Record<Language, string>> = {
  // App
  "app.title": { en: "Flour Mill Manager", ur: "فلور مل مینیجر" },

  // Auth
  "auth.login": { en: "Log In", ur: "لاگ ان" },
  "auth.signup": { en: "Sign Up", ur: "سائن اپ" },
  "auth.email": { en: "Email", ur: "ای میل" },
  "auth.password": { en: "Password", ur: "پاس ورڈ" },
  "auth.fullName": { en: "Full Name", ur: "پورا نام" },
  "auth.noAccount": { en: "Don't have an account?", ur: "اکاؤنٹ نہیں ہے؟" },
  "auth.hasAccount": { en: "Already have an account?", ur: "اکاؤنٹ پہلے سے ہے؟" },
  "auth.loggingIn": { en: "Logging in...", ur: "لاگ ان ہو رہا ہے..." },
  "auth.signingUp": { en: "Signing up...", ur: "سائن اپ ہو رہا ہے..." },
  "auth.logout": { en: "Logout", ur: "لاگ آؤٹ" },
  "auth.checkEmail": { en: "Check your email for a confirmation link.", ur: "تصدیقی لنک کے لیے اپنا ای میل چیک کریں۔" },

  // Nav
  "nav.dashboard": { en: "Dashboard", ur: "ڈیش بورڈ" },
  "nav.contacts": { en: "Contacts", ur: "روابط" },
  "nav.products": { en: "Products", ur: "مصنوعات" },
  "nav.sales": { en: "Sales", ur: "فروخت" },
  "nav.purchases": { en: "Purchases", ur: "خریداری" },
  "nav.production": { en: "Production", ur: "پیداوار" },
  "nav.reports": { en: "Reports", ur: "رپورٹس" },

  // Reports
  "reports.title": { en: "Reports & Analytics", ur: "رپورٹس اور تجزیات" },
  "reports.topProducts": { en: "Top Products", ur: "سب سے زیادہ فروخت" },
  "reports.salesVsPurchases": { en: "Sales vs Purchases", ur: "فروخت بمقابلہ خریداری" },
  "reports.profitMargins": { en: "Profit Margins", ur: "منافع مارجن" },
  "reports.agingReport": { en: "Aging Report", ur: "واجبات رپورٹ" },
  "reports.thisMonth": { en: "This Month", ur: "اس مہینے" },
  "reports.lastMonth": { en: "Last Month", ur: "پچھلا مہینہ" },
  "reports.last90Days": { en: "Last 90 Days", ur: "آخری 90 دن" },
  "reports.last6Months": { en: "Last 6 Months", ur: "آخری 6 مہینے" },
  "reports.last12Months": { en: "Last 12 Months", ur: "آخری 12 مہینے" },
  "reports.last24Months": { en: "Last 24 Months", ur: "آخری 24 مہینے" },
  "reports.revenue": { en: "Revenue (₨)", ur: "آمدنی (₨)" },
  "reports.revenueLabel": { en: "Revenue", ur: "آمدنی" },
  "reports.breakdownTitle": { en: "Breakdown by Business Unit and Category", ur: "کاروباری اکائی اور کیٹیگری کے لحاظ سے تفصیل" },
  "reports.unitsSold": { en: "Units Sold", ur: "فروخت شدہ اکائیاں" },
  "reports.change": { en: "% Change", ur: "% تبدیلی" },
  "reports.totalSales": { en: "Total Sales", ur: "کل فروخت" },
  "reports.totalPurchases": { en: "Total Purchases", ur: "کل خریداری" },
  "reports.netDifference": { en: "Net Difference", ur: "خالص فرق" },
  "reports.overallMargin": { en: "Overall Margin", ur: "مجموعی مارجن" },
  "reports.marginPct": { en: "Margin %", ur: "مارجن %" },
  "reports.receivables": { en: "Receivables", ur: "وصولیاں" },
  "reports.payables": { en: "Payables", ur: "واجبات" },
  "reports.agingDistribution": { en: "Aging Distribution", ur: "واجبات کی تقسیم" },
  "reports.overdueInvoices": { en: "Overdue Invoices", ur: "واجب الادا انوائسز" },
  "reports.dueDate": { en: "Due Date", ur: "مقررہ تاریخ" },
  "reports.amountDue": { en: "Amount Due", ur: "واجب رقم" },
  "reports.daysOverdue": { en: "Days Overdue", ur: "تاخیر کے دن" },
  "reports.byDays": { en: "By Days", ur: "دنوں کے مطابق" },
  "reports.byAmount": { en: "By Amount", ur: "رقم کے مطابق" },
  "reports.financial": { en: "Financial", ur: "مالیاتی" },
  "reports.profitLoss": { en: "Profit & Loss", ur: "نفع و نقصان" },
  "reports.profitLossStatement": { en: "P&L Statement", ur: "نفع و نقصان بیان" },
  "reports.cashFlow": { en: "Cash Flow", ur: "نقد بہاؤ" },
  "reports.cashFlowStatement": { en: "Cash Flow Statement", ur: "نقد بہاؤ بیان" },
  "reports.balanceSheet": { en: "Balance Sheet", ur: "بیلنس شیٹ" },
  "reports.totalRevenue": { en: "Total Revenue", ur: "کل آمدنی" },
  "reports.cogs": { en: "Cost of Goods Sold", ur: "اشیاء کی لاگت" },
  "reports.grossProfit": { en: "Gross Profit", ur: "مجموعی منافع" },
  "reports.netProfit": { en: "Net Profit", ur: "خالص منافع" },
  "reports.discountsGiven": { en: "Discounts Given", ur: "دی گئی رعایتیں" },
  "reports.transportExpenses": { en: "Transport Expenses", ur: "ٹرانسپورٹ اخراجات" },
  "reports.lineItem": { en: "Line Item", ur: "آئٹم" },
  "reports.totalInflow": { en: "Total Cash In", ur: "کل نقد آمد" },
  "reports.totalOutflow": { en: "Total Cash Out", ur: "کل نقد اخراج" },
  "reports.netCashFlow": { en: "Net Cash Flow", ur: "خالص نقد بہاؤ" },
  "reports.cashInflows": { en: "Cash Inflows", ur: "نقد آمد" },
  "reports.cashOutflows": { en: "Cash Outflows", ur: "نقد اخراج" },
  "reports.salePaymentsReceived": { en: "Sale Payments Received", ur: "فروخت کی وصول شدہ ادائیگیاں" },
  "reports.purchasePaymentsMade": { en: "Purchase Payments Made", ur: "خریداری کی ادائیگیاں" },
  "reports.totalAssets": { en: "Total Assets", ur: "کل اثاثے" },
  "reports.currentAssets": { en: "Current Assets", ur: "موجودہ اثاثے" },
  "reports.currentLiabilities": { en: "Current Liabilities", ur: "موجودہ واجبات" },
  "reports.totalLiabilities": { en: "Total Liabilities", ur: "کل واجبات" },
  "reports.equity": { en: "Equity", ur: "ایکوئٹی" },
  "reports.assets": { en: "Assets", ur: "اثاثے" },
  "reports.liabilities": { en: "Liabilities", ur: "واجبات" },
  "reports.accountsReceivable": { en: "Accounts Receivable", ur: "قابل وصول رقوم" },
  "reports.accountsPayable": { en: "Accounts Payable", ur: "قابل ادائیگی رقوم" },
  "reports.inventoryValue": { en: "Inventory Value", ur: "انوینٹری کی قیمت" },
  "reports.last3Months": { en: "Last 3 Months", ur: "آخری 3 مہینے" },
  "reports.professionalView": { en: "Professional View", ur: "پیشہ ورانہ نظارہ" },
  "reports.summaryView": { en: "Summary View", ur: "خلاصہ نظارہ" },

  // Inventory
  "nav.inventory": { en: "Inventory", ur: "انوینٹری" },
  "nav.units": { en: "Units", ur: "اکائیاں" },
  "units.title": { en: "Measurement Units", ur: "پیمائش کی اکائیاں" },
  "units.add": { en: "Add Unit", ur: "اکائی شامل کریں" },
  "units.name": { en: "Name (English)", ur: "نام (انگریزی)" },
  "units.nameUr": { en: "Name (Urdu)", ur: "نام (اردو)" },
  "units.kgValue": { en: "KG Value", ur: "کلوگرام قدر" },
  "units.kgValueHint": { en: "Define how many KG each unit equals (e.g. 1 Maund = 40 KG)", ur: "ہر اکائی کتنے کلوگرام کے برابر ہے (مثلاً 1 من = 40 کلو)" },
  "units.subUnit": { en: "Sub-Unit", ur: "ذیلی اکائی" },
  "units.subUnitHint": { en: "Optional smaller unit for split entry (e.g. Maund → KG)", ur: "تقسیم اندراج کے لیے اختیاری چھوٹی اکائی (مثلاً من → کلو)" },
  "units.noSubUnit": { en: "None", ur: "کوئی نہیں" },
  "inventory.title": { en: "Stock & Inventory", ur: "اسٹاک اور انوینٹری" },
  "inventory.replenishment": { en: "Replenishment", ur: "بھرپائی" },
  "inventory.batchTracking": { en: "Batch Tracking", ur: "بیچ ٹریکنگ" },
  "inventory.currentStock": { en: "Current Stock", ur: "موجودہ اسٹاک" },
  "inventory.minLevel": { en: "Min Level", ur: "کم از کم سطح" },
  "inventory.criticalItems": { en: "Critical Items", ur: "اہم اشیاء" },
  "inventory.warningItems": { en: "Warning Items", ur: "انتباہی اشیاء" },
  "inventory.totalTracked": { en: "Total Tracked", ur: "کل ٹریک شدہ" },
  "inventory.lowStockChart": { en: "Low Stock Items", ur: "کم اسٹاک اشیاء" },
  "inventory.replenishmentTable": { en: "Replenishment Recommendations", ur: "بھرپائی کی سفارشات" },
  "inventory.velocity": { en: "Sales Velocity", ur: "فروخت کی رفتار" },
  "inventory.daysLeft": { en: "Days Left", ur: "باقی دن" },
  "inventory.reorderQty": { en: "Reorder Qty", ur: "دوبارہ آرڈر مقدار" },
  "inventory.critical": { en: "Critical", ur: "اہم" },
  "inventory.warning": { en: "Warning", ur: "انتباہ" },
  "inventory.ok": { en: "OK", ur: "ٹھیک" },
  "inventory.addBatch": { en: "Add Batch", ur: "بیچ شامل کریں" },
  "inventory.batchNumber": { en: "Batch Number", ur: "بیچ نمبر" },
  "inventory.supplier": { en: "Supplier", ur: "فراہم کنندہ" },
  "inventory.remaining": { en: "Remaining", ur: "باقی" },
  "inventory.manufactureDate": { en: "Manufacture Date", ur: "تیاری کی تاریخ" },
  "inventory.qualityNotes": { en: "Quality Notes", ur: "معیار کے نوٹس" },
  "inventory.batchDetail": { en: "Batch Details", ur: "بیچ کی تفصیلات" },

  // Cash Closing
  "reports.cashClosing": { en: "Cash Closing", ur: "نقد بندش" },
  "reports.totalCashIn": { en: "Total Cash In", ur: "کل نقد آمد" },
  "reports.totalCashOut": { en: "Total Cash Out", ur: "کل نقد اخراج" },
  "reports.cashInHand": { en: "Cash in Hand", ur: "نقد رقم" },
  "reports.creditGiven": { en: "Credit Given", ur: "دیا گیا ادھار" },
  "reports.creditTaken": { en: "Credit Taken", ur: "لیا گیا ادھار" },
  "reports.saleInvoicesToday": { en: "Sale Invoices Today", ur: "آج کی فروخت انوائسز" },
  "reports.purchaseInvoicesToday": { en: "Purchase Invoices Today", ur: "آج کی خریداری انوائسز" },
  "reports.followUpPayments": { en: "Follow-up Payments", ur: "بعد کی ادائیگیاں" },
  "reports.received": { en: "Received", ur: "وصول شدہ" },
  "reports.paid": { en: "Paid", ur: "ادا شدہ" },
  "reports.exportCSV": { en: "Export CSV", ur: "CSV ڈاؤن لوڈ" },
  "reports.fromDate": { en: "From", ur: "سے" },
  "reports.toDate": { en: "To", ur: "تک" },

  // WhatsApp
  "invoice.shareWhatsApp": { en: "Share on WhatsApp", ur: "واٹس ایپ پر شیئر کریں" },

  // Dashboard
  "dashboard.todaySales": { en: "Today's Sales", ur: "آج کی فروخت" },
  "dashboard.todayPurchases": { en: "Today's Purchases", ur: "آج کی خریداری" },
  "dashboard.totalCash": { en: "Cash in Hand", ur: "نقد موجود" },
  "dashboard.receivables": { en: "Receivables", ur: "وصولیاں" },
  "dashboard.payables": { en: "Payables", ur: "واجبات" },
  "dashboard.lowStock": { en: "Low Stock Alerts", ur: "کم اسٹاک الرٹس" },
  "dashboard.overdueInvoices": { en: "Overdue Invoices", ur: "واجب الادا انوائسز" },
  "dashboard.monthlyProfit": { en: "Monthly Profit", ur: "ماہانہ منافع" },
  "dashboard.inventoryBreakdown": { en: "Inventory Value Breakdown", ur: "انوینٹری ویلیو تفصیل" },
  "dashboard.fromPurchases": { en: "From purchases", ur: "خریداری سے" },
  "dashboard.usingDefaultPrice": { en: "Default price", ur: "ڈیفالٹ قیمت" },
  "dashboard.missingCost": { en: "Missing cost", ur: "لاگت دستیاب نہیں" },
  "dashboard.productCount": { en: "{0} products", ur: "{0} مصنوعات" },
  "dashboard.warningCount": { en: "{0} warnings", ur: "{0} انتباہات" },
  "dashboard.clickToSeeDetails": { en: "Click to see details", ur: "تفصیلات کے لیے کلک کریں" },
  "dashboard.avgCost": { en: "Avg Cost", ur: "اوسط لاگت" },
  "dashboard.costSource": { en: "Cost Basis", ur: "لاگت کی بنیاد" },
  "dashboard.cashReceipts": { en: "Cash Receipts", ur: "نقد وصولیاں" },
  "dashboard.cashPayments": { en: "Cash Payments", ur: "نقد ادائیگیاں" },
  "dashboard.cashExpenses": { en: "Cash Expenses", ur: "نقد اخراجات" },
  "dashboard.netCashInHand": { en: "Net Cash in Hand", ur: "خالص نقد موجود" },
  "voucher.contact": { en: "Contact", ur: "رابطہ" },
  "voucher.transferIn": { en: "Transfer In", ur: "منتقلی آمد" },
  "voucher.transferOut": { en: "Transfer Out", ur: "منتقلی اخراج" },

  // Production
  "production.create": { en: "New Conversion", ur: "نئی تبدیلی" },
  "production.source": { en: "Source Product", ur: "ذریعہ مصنوعات" },
  "production.sourceQty": { en: "Source Qty (KG)", ur: "ذریعہ مقدار (KG)" },
  "production.outputs": { en: "Output Products", ur: "پیداوار مصنوعات" },
  "production.history": { en: "Production History", ur: "پیداوار کی تاریخ" },

  // Contacts
  "contacts.title": { en: "Contacts", ur: "روابط" },
  "contacts.add": { en: "Add Contact", ur: "رابطہ شامل کریں" },
  "contacts.name": { en: "Name", ur: "نام" },
  "contacts.phone": { en: "Phone", ur: "فون" },
  "contacts.city": { en: "City", ur: "شہر" },
  "contacts.address": { en: "Address", ur: "پتہ" },
  "contacts.type": { en: "Type", ur: "قسم" },
  "contacts.customer": { en: "Customer", ur: "گاہک" },
  "contacts.supplier": { en: "Supplier", ur: "فراہم کنندہ" },
  "contacts.both": { en: "Both", ur: "دونوں" },
  "contacts.broker": { en: "Broker", ur: "دلال" },
  "contacts.bank": { en: "Bank", ur: "بینک" },
  "contacts.addNewType": { en: "＋ Add New Type", ur: "＋ نئی قسم شامل کریں" },
  "contacts.newTypeName": { en: "New type name", ur: "نئی قسم کا نام" },
  "contacts.typeCreated": { en: "Contact type created", ur: "رابطے کی قسم بنائی گئی" },
  "contacts.creditLimit": { en: "Credit Limit", ur: "کریڈٹ حد" },
  "contacts.openingBalance": { en: "Opening Balance", ur: "ابتدائی بیلنس" },
  "contacts.paymentTerms": { en: "Payment Terms (days)", ur: "ادائیگی کی شرائط (دن)" },
  "contacts.filterByType": { en: "Filter by Type", ur: "قسم کے مطابق فلٹر" },
  "contacts.filterByCity": { en: "Filter by City", ur: "شہر کے مطابق فلٹر" },
  "common.all": { en: "All", ur: "سب" },

  // Products
  "products.title": { en: "Products & Inventory", ur: "مصنوعات اور انوینٹری" },
  "products.add": { en: "Add Product", ur: "مصنوعات شامل کریں" },
  "products.name": { en: "Product Name", ur: "مصنوعات کا نام" },
  "products.category": { en: "Category", ur: "زمرہ" },
  "products.unit": { en: "Unit", ur: "اکائی" },
  "products.stock": { en: "Stock", ur: "اسٹاک" },
  "products.minStock": { en: "Min Stock Level", ur: "کم از کم اسٹاک" },
  "products.price": { en: "Default Price (₨)", ur: "طے شدہ قیمت (₨)" },
  "products.stockValue": { en: "Stock Value", ur: "اسٹاک قیمت" },
  "products.tradeable": { en: "Tradeable", ur: "تجارتی" },

  // Invoices
  "invoice.sales": { en: "Sales Invoices", ur: "فروخت انوائسز" },
  "invoice.purchases": { en: "Purchase Invoices", ur: "خریداری انوائسز" },
  "invoice.create": { en: "Create Invoice", ur: "انوائس بنائیں" },
  "invoice.number": { en: "Invoice #", ur: "انوائس نمبر" },
  "invoice.date": { en: "Date", ur: "تاریخ" },
  "invoice.contact": { en: "Contact", ur: "رابطہ" },
  "invoice.total": { en: "Total", ur: "کل" },
  "invoice.status": { en: "Status", ur: "حالت" },
  "invoice.paid": { en: "Paid", ur: "ادا شدہ" },
  "invoice.pending": { en: "Pending", ur: "زیر التوا" },
  "invoice.partial": { en: "Partial", ur: "جزوی" },
  "invoice.credit": { en: "Credit", ur: "ادھار" },
  "invoice.selectContact": { en: "Select contact", ur: "رابطہ منتخب کریں" },
  "invoice.addItem": { en: "Add Item", ur: "آئٹم شامل کریں" },
  "invoice.addItems": { en: "Add at least one valid item", ur: "کم از کم ایک آئٹم شامل کریں" },
  "invoice.quantity": { en: "Qty", ur: "مقدار" },
  "invoice.mainQty": { en: "Main Qty", ur: "اصل مقدار" },
  "invoice.extraQty": { en: "Extra", ur: "اضافی" },
  "invoice.subQty": { en: "Sub-Unit Qty", ur: "ذیلی مقدار" },
  "invoice.totalKg": { en: "Total: {0} {1}", ur: "کل: {0} {1}" },
  "invoice.price": { en: "Price", ur: "قیمت" },
  "invoice.subtotal": { en: "Subtotal", ur: "ذیلی کل" },
  "invoice.discount": { en: "Discount (₨)", ur: "رعایت (₨)" },
  "invoice.transport": { en: "Transport (₨)", ur: "ٹرانسپورٹ (₨)" },
  "invoice.paymentMethod": { en: "Payment", ur: "ادائیگی" },
  "invoice.amountPaid": { en: "Amount Paid", ur: "ادا شدہ رقم" },
  "invoice.balanceDue": { en: "Balance Due", ur: "باقی رقم" },

  // Broker
  "invoice.broker": { en: "Broker", ur: "دلال" },
  "invoice.selectBroker": { en: "Select broker", ur: "دلال منتخب کریں" },
  "invoice.searchBroker": { en: "Search broker...", ur: "دلال تلاش کریں..." },
  "invoice.noBroker": { en: "No broker found", ur: "کوئی دلال نہیں ملا" },
  "invoice.commissionRate": { en: "Commission Rate (₨)", ur: "کمیشن شرح (₨)" },
  "invoice.commissionUnit": { en: "Commission Per", ur: "کمیشن فی" },
  "invoice.commissionTotal": { en: "Commission Total", ur: "کل کمیشن" },
  "invoice.brokerSection": { en: "Broker & Commission", ur: "دلال اور کمیشن" },

  // Payment
  "payment.record": { en: "Record Payment", ur: "ادائیگی درج کریں" },
  "payment.amount": { en: "Amount", ur: "رقم" },
  "payment.history": { en: "Payment History", ur: "ادائیگی کی تاریخ" },
  "payment.recorded": { en: "Payment recorded", ur: "ادائیگی درج ہو گئی" },
  "payment.invalidAmount": { en: "Invalid amount", ur: "غلط رقم" },

  // Filters
  "filter.all": { en: "All", ur: "سب" },
  "filter.from": { en: "From", ur: "سے" },
  "filter.to": { en: "To", ur: "تک" },
  "filter.clear": { en: "Clear", ur: "صاف کریں" },

  // Expenses
  "nav.expenses": { en: "Expenses", ur: "اخراجات" },
  "expenses.title": { en: "Expenses", ur: "اخراجات" },
  "expenses.new": { en: "New Expense", ur: "نیا خرچہ" },
  "expenses.form": { en: "Expense Details", ur: "خرچے کی تفصیلات" },
  "expenses.category": { en: "Category", ur: "زمرہ" },
  "expenses.selectCategory": { en: "Select category", ur: "زمرہ منتخب کریں" },
  "expenses.paymentMethod": { en: "Payment Method", ur: "ادائیگی کا طریقہ" },
  "expenses.cash": { en: "Cash", ur: "نقد" },
  "expenses.bank": { en: "Bank", ur: "بینک" },
  "expenses.other": { en: "Other", ur: "دیگر" },
  "expenses.saved": { en: "Expense recorded", ur: "خرچہ درج ہو گیا" },
  "expenses.total": { en: "Total Expenses", ur: "کل اخراجات" },
  "expenses.notesPlaceholder": { en: "Optional notes...", ur: "اختیاری نوٹس..." },
  "expenses.totalToday": { en: "Today's Expenses", ur: "آج کے اخراجات" },
  "expenses.totalMonth": { en: "This Month", ur: "اس مہینے" },
  "expenses.totalAll": { en: "Total (Filtered)", ur: "کل (فلٹر شدہ)" },
  "expenses.filters": { en: "Filters", ur: "فلٹرز" },
  "expenses.dateFrom": { en: "From", ur: "سے" },
  "expenses.dateTo": { en: "To", ur: "تک" },
  "expenses.allCategories": { en: "All Categories", ur: "تمام زمرے" },
  "expenses.allMethods": { en: "All Methods", ur: "تمام طریقے" },
  "expenses.categoryBreakdown": { en: "Category Breakdown", ur: "زمرہ وار تفصیل" },
  "expenses.validationCategory": { en: "Please select a category", ur: "براہ کرم زمرہ منتخب کریں" },
  "expenses.validationAmount": { en: "Please enter a valid amount", ur: "براہ کرم درست رقم درج کریں" },
  "expenses.search": { en: "Search notes...", ur: "نوٹس تلاش کریں..." },
  "reports.operatingExpenses": { en: "Operating Expenses", ur: "آپریٹنگ اخراجات" },

  // Adjustments
  "adjustments.title": { en: "Stock Adjustments", ur: "اسٹاک ایڈجسٹمنٹ" },
  "adjustments.new": { en: "New Adjustment", ur: "نئی ایڈجسٹمنٹ" },
  "adjustments.form": { en: "Adjustment Details", ur: "ایڈجسٹمنٹ کی تفصیلات" },
  "adjustments.number": { en: "Adjustment #", ur: "ایڈجسٹمنٹ نمبر" },
  "adjustments.type": { en: "Type", ur: "قسم" },
  "adjustments.increase": { en: "Increase", ur: "اضافہ" },
  "adjustments.decrease": { en: "Decrease", ur: "کمی" },
  "adjustments.quantity": { en: "Quantity", ur: "مقدار" },
  "adjustments.reason": { en: "Reason", ur: "وجہ" },
  "adjustments.selectReason": { en: "Select reason", ur: "وجہ منتخب کریں" },
  "adjustments.selectProduct": { en: "Select product", ur: "مصنوعات منتخب کریں" },
  "adjustments.batch": { en: "Batch", ur: "بیچ" },
  "adjustments.optional": { en: "Optional", ur: "اختیاری" },
  "adjustments.selectBatch": { en: "Select batch", ur: "بیچ منتخب کریں" },
  "adjustments.noBatch": { en: "No specific batch", ur: "کوئی مخصوص بیچ نہیں" },
  "adjustments.notes": { en: "Notes", ur: "نوٹس" },
  "adjustments.notesPlaceholder": { en: "Optional notes about this adjustment...", ur: "اس ایڈجسٹمنٹ کے بارے میں نوٹس..." },
  "adjustments.saved": { en: "Adjustment recorded and stock updated", ur: "ایڈجسٹمنٹ درج اور اسٹاک اپ ڈیٹ ہو گیا" },
  "adjustments.currentStock": { en: "Current Stock", ur: "موجودہ اسٹاک" },
  "adjustments.afterStock": { en: "After Adjustment", ur: "ایڈجسٹمنٹ کے بعد" },
  "adjustments.selectProductHint": { en: "Select a product to see stock info", ur: "اسٹاک دیکھنے کے لیے پروڈکٹ منتخب کریں" },
  "adjustments.negativeWarning": { en: "Stock will go negative", ur: "اسٹاک منفی ہو جائے گا" },
  "adjustments.validationProduct": { en: "Please select a product", ur: "براہ کرم پروڈکٹ منتخب کریں" },
  "adjustments.validationQuantity": { en: "Please enter a quantity", ur: "براہ کرم مقدار درج کریں" },
  "adjustments.validationReason": { en: "Please select a reason", ur: "براہ کرم وجہ منتخب کریں" },
  "adjustments.details": { en: "Adjustment Details", ur: "ایڈجسٹمنٹ کی تفصیلات" },

  // Ledger
  "ledger.title": { en: "Financial Ledger", ur: "مالی کھاتہ" },
  "ledger.totalSales": { en: "Total Sales", ur: "کل فروخت" },
  "ledger.totalPurchases": { en: "Total Purchases", ur: "کل خریداری" },
  "ledger.totalPaid": { en: "Total Paid", ur: "کل ادائیگی" },
  "ledger.totalOutstanding": { en: "Outstanding", ur: "واجب الادا" },
  "ledger.lastTransaction": { en: "Last Transaction", ur: "آخری لین دین" },
  "ledger.invoiceHistory": { en: "Invoice History", ur: "انوائس ہسٹری" },
  "ledger.downloadStatement": { en: "Download Statement", ur: "بیان ڈاؤن لوڈ" },

  // Dashboard Intelligence
  "dashboard.topProducts": { en: "Top Selling Products", ur: "سب سے زیادہ فروخت ہونے والی مصنوعات" },
  "dashboard.topCustomers": { en: "Top Customers", ur: "اہم گاہک" },
  "dashboard.recentActivity": { en: "Recent Activity", ur: "حالیہ سرگرمی" },
  "dashboard.inactiveProducts": { en: "No Sales (30 Days)", ur: "بغیر فروخت (30 دن)" },
  "dashboard.inventoryValue": { en: "Inventory Value", ur: "انوینٹری کی قیمت" },
  "dashboard.subtitle": { en: "Overview of your business metrics", ur: "آپ کے کاروبار کے اعداد و شمار کا خلاصہ" },
  "dashboard.saleCreated": { en: "Sale created", ur: "فروخت بنائی گئی" },
  "dashboard.purchaseCreated": { en: "Purchase created", ur: "خریداری بنائی گئی" },
  "dashboard.paymentRecorded": { en: "Payment recorded", ur: "ادائیگی درج" },
  "dashboard.receiptVoucherCreated": { en: "Receipt Voucher created", ur: "وصولی واؤچر بنایا گیا" },
  "dashboard.paymentVoucherCreated": { en: "Payment Voucher created", ur: "ادائیگی واؤچر بنایا گیا" },
  "dashboard.directReceiptVoucher": { en: "Direct Receipt Voucher", ur: "براہ راست وصولی واؤچر" },
  "dashboard.directPaymentVoucher": { en: "Direct Payment Voucher", ur: "براہ راست ادائیگی واؤچر" },
  "expenses.addCategory": { en: "＋ Add new category", ur: "＋ نئی کیٹیگری شامل کریں" },
  "expenses.newCategoryName": { en: "New category name", ur: "نئی کیٹیگری کا نام" },
  "dashboard.allBusinessUnits": { en: "All Business Units", ur: "تمام کاروباری اکائیاں" },
  "dashboard.adjustmentCreated": { en: "Adjustment created", ur: "ایڈجسٹمنٹ بنائی گئی" },
  "dashboard.expenseCreated": { en: "Expense recorded", ur: "خرچہ درج" },

  // Search
  "search.placeholder": { en: "Search...", ur: "تلاش کریں..." },
  "search.results": { en: "Results", ur: "نتائج" },
  "search.contact": { en: "Contact", ur: "رابطہ" },
  "search.invoice": { en: "Invoice", ur: "انوائس" },
  "search.product": { en: "Product", ur: "مصنوعات" },
  "search.batch": { en: "Batch", ur: "بیچ" },

  // Invoice form extras
  "invoice.invoiceDate": { en: "Invoice Date", ur: "انوائس کی تاریخ" },
  "invoice.notes": { en: "Notes", ur: "نوٹس" },
  "invoice.notesPlaceholder": { en: "Optional notes...", ur: "اختیاری نوٹس..." },
  "invoice.searchContact": { en: "Search contact...", ur: "رابطہ تلاش کریں..." },
  "invoice.searchProduct": { en: "Search product...", ur: "مصنوعات تلاش کریں..." },
  "invoice.emptyItems": { en: "No items added yet", ur: "ابھی تک کوئی آئٹم نہیں" },
  "invoice.emptyItemsHint": { en: "Add your first item to get started", ur: "شروع کرنے کے لیے پہلا آئٹم شامل کریں" },
  "invoice.partySection": { en: "Party", ur: "پارٹی" },
  "invoice.itemsSection": { en: "Items", ur: "آئٹمز" },
  "invoice.summarySection": { en: "Summary", ur: "خلاصہ" },
  "invoice.paymentSection": { en: "Payment", ur: "ادائیگی" },
  "invoice.stockAvailable": { en: "Stock", ur: "اسٹاک" },
  "invoice.noContact": { en: "No contact found", ur: "کوئی رابطہ نہیں ملا" },
  "invoice.noProduct": { en: "No product found", ur: "کوئی مصنوعات نہیں ملی" },
  "invoice.row": { en: "Row", ur: "قطار" },

  // Notifications
  "notifications.title": { en: "Notifications", ur: "اطلاعات" },
  "notifications.none": { en: "No notifications", ur: "کوئی اطلاع نہیں" },
  "notifications.lowStock": { en: "Low Stock", ur: "کم اسٹاک" },
  "notifications.overdueInvoice": { en: "Overdue Invoice", ur: "واجب الادا انوائس" },
  "notifications.batchExpiry": { en: "Batch Expiring", ur: "بیچ ختم ہونے والا" },

  // Common
  "common.total": { en: "Total", ur: "کل" },
  "common.save": { en: "Save", ur: "محفوظ کریں" },
  "common.saved": { en: "Saved", ur: "محفوظ ہو گیا" },
  "common.updated": { en: "Updated", ur: "اپ ڈیٹ ہو گیا" },
  "common.deleted": { en: "Deleted", ur: "حذف ہو گیا" },
  "common.cancel": { en: "Cancel", ur: "منسوخ" },
  "common.delete": { en: "Delete", ur: "حذف کریں" },
  "common.edit": { en: "Edit", ur: "ترمیم" },
  "common.actions": { en: "Actions", ur: "عمل" },
  "common.search": { en: "Search...", ur: "تلاش..." },
  "common.noData": { en: "No data found", ur: "کوئی ڈیٹا نہیں ملا" },
  "common.loading": { en: "Loading...", ur: "لوڈ ہو رہا ہے..." },
  "common.currency": { en: "₨", ur: "₨" },
  "common.confirmDelete": { en: "Are you sure?", ur: "کیا آپ کو یقین ہے؟" },
  "common.confirmDeleteDesc": { en: "This action cannot be undone.", ur: "یہ عمل واپس نہیں ہو سکتا۔" },
  "common.deleteInUse": { en: "Cannot delete — this record is used in existing transactions.", ur: "حذف نہیں ہو سکتا — یہ ریکارڈ موجودہ لین دین میں استعمال ہو رہا ہے۔" },
  "production.invalidOutputs": { en: "All outputs must have a product and quantity > 0", ur: "تمام پیداوار میں مصنوعات اور مقدار > 0 ہونی چاہیے" },
  "expenses.edit": { en: "Edit Expense", ur: "خرچے میں ترمیم" },
  "expenses.deleteConfirm": { en: "Delete this expense?", ur: "یہ خرچہ حذف کریں؟" },

  // Account Categories
  "accountCategory.label": { en: "Account Category", ur: "اکاؤنٹ کیٹیگری" },
  "accountCategory.cash": { en: "Cash in Hand", ur: "نقد رقم" },
  "accountCategory.bank": { en: "Bank Accounts", ur: "بینک اکاؤنٹس" },
  "accountCategory.closing": { en: "Will Be Close Accounts", ur: "بند ہونے والے اکاؤنٹس" },
  "accountCategory.customer": { en: "Customer Accounts", ur: "کسٹمر اکاؤنٹس" },
  "accountCategory.supplier": { en: "Party / Supplier", ur: "سپلائر" },
  "accountCategory.employee": { en: "Employee Accounts", ur: "ملازمین کے اکاؤنٹس" },
  "accountCategory.salesIncome": { en: "Sales / Income Accounts", ur: "سیلز / آمدنی" },
  "accountCategory.purchase": { en: "Purchase Accounts", ur: "خریداری" },
  "accountCategory.directExpense": { en: "Direct Expenses", ur: "براہ راست اخراجات" },
  "accountCategory.unassigned": { en: "Unassigned", ur: "غیر مختص" },
  "accountCategory.addNew": { en: "+ Add New Category", ur: "+ نئی کیٹیگری شامل کریں" },
  "accountCategory.newName": { en: "New category name", ur: "نئی کیٹیگری کا نام" },

  // Business Units
  "businessUnit.label": { en: "Business Unit", ur: "کاروباری اکائی" },
  "businessUnit.flourMill": { en: "Al Madina Flour Mill", ur: "المدینہ فلور مل" },
  "businessUnit.riceHullar": { en: "Al Madina Rice Hullar", ur: "المدینہ رائس ہلر" },
  "businessUnit.unassigned": { en: "Unassigned", ur: "غیر مختص" },

  // Opening Balance
  "contacts.openingBalanceDate": { en: "Opening Balance Date", ur: "ابتدائی بیلنس کی تاریخ" },
  "reports.openingReceivables": { en: "Opening Receivables", ur: "ابتدائی وصولیاں" },
  "reports.openingPayables": { en: "Opening Payables", ur: "ابتدائی واجبات" },
  "ledger.openingBalance": { en: "Opening Balance", ur: "ابتدائی بیلنس" },

  // Financial Categories (Phase 1)
  "dashboard.bankBalance": { en: "Bank Balance", ur: "بینک بیلنس" },
  "reports.bankAccounts": { en: "Bank Accounts", ur: "بینک اکاؤنٹس" },
  "reports.customerReceivables": { en: "Customer Receivables", ur: "صارفین واجب الادا" },
  "reports.supplierPayables": { en: "Supplier Payables", ur: "سپلائر واجبات" },
  "reports.employeeReceivables": { en: "Employee Receivables", ur: "ملازمین بقایا" },
  "reports.capitalEquity": { en: "Capital / Equity", ur: "سرمایہ" },
  "reports.closingAccounts": { en: "Closing Accounts", ur: "بند اکاؤنٹس" },
  "reports.retainedEarnings": { en: "Retained Earnings", ur: "جمع شدہ منافع" },
  "reports.cashExpenses": { en: "Operating Expenses (Cash)", ur: "آپریٹنگ اخراجات (نقد)" },
  "dashboard.employeeAdvances": { en: "Employee Advances", ur: "ملازمین ایڈوانس" },
  "common.showMore": { en: "Show more", ur: "مزید دکھائیں" },
  "common.showLess": { en: "Show less", ur: "کم دکھائیں" },
  "dashboard.noCostData": { en: "⚠ No cost data", ur: "⚠ لاگت کا ڈیٹا نہیں" },
  "dashboard.includesOpeningStock": { en: "Includes opening stock", ur: "ابتدائی اسٹاک شامل ہے" },

  // Vouchers
  "nav.receiptVouchers": { en: "Receipt Vouchers", ur: "رسید واؤچرز" },
  "nav.paymentVouchers": { en: "Payment Vouchers", ur: "ادائیگی واؤچرز" },
  "voucher.receipt": { en: "Receipt Voucher", ur: "رسید واؤچر" },
  "voucher.payment": { en: "Payment Voucher", ur: "ادائیگی واؤچر" },
  "voucher.history": { en: "Voucher History", ur: "واؤچر ہسٹری" },
  "voucher.method": { en: "Payment Method", ur: "ادائیگی کا طریقہ" },
  "voucher.cash": { en: "Cash", ur: "نقد" },
  "voucher.bank": { en: "Bank", ur: "بینک" },
  "voucher.totalPaid": { en: "Total Paid", ur: "کل ادائیگی" },
  "voucher.remaining": { en: "Remaining Balance", ur: "باقی رقم" },
  "voucher.addReceipt": { en: "Add Receipt Voucher", ur: "رسید واؤچر شامل کریں" },
  "voucher.addPayment": { en: "Add Payment Voucher", ur: "ادائیگی واؤچر شامل کریں" },
  "voucher.notes": { en: "Notes", ur: "نوٹس" },
  "voucher.invoiceTotal": { en: "Invoice Total", ur: "انوائس کل" },
  "voucher.allMethods": { en: "All Methods", ur: "تمام طریقے" },
  "voucher.title": { en: "Vouchers", ur: "واؤچرز" },
  "voucher.newVoucher": { en: "New Voucher", ur: "نیا واؤچر" },
  "voucher.type": { en: "Voucher Type", ur: "واؤچر کی قسم" },
  "voucher.invoice": { en: "Invoice", ur: "انوائس" },
  "voucher.optional": { en: "optional", ur: "اختیاری" },
  "voucher.noInvoice": { en: "No invoice (Direct Voucher)", ur: "کوئی انوائس نہیں (براہ راست واؤچر)" },
  "voucher.directLabel": { en: "This will be saved as a Direct Voucher", ur: "یہ براہ راست واؤچر کے طور پر محفوظ ہوگا" },
  "voucher.direct": { en: "Direct Voucher", ur: "براہ راست واؤچر" },
  "voucher.directReceipt": { en: "Direct Receipt", ur: "براہ راست رسید" },
  "voucher.directPayment": { en: "Direct Payment", ur: "براہ راست ادائیگی" },
  "voucher.voucherNumber": { en: "Voucher #", ur: "واؤچر نمبر" },
  "voucher.selectBank": { en: "Select bank account", ur: "بینک اکاؤنٹ منتخب کریں" },
  "voucher.bankRequired": { en: "Please select a bank account", ur: "براہ کرم بینک اکاؤنٹ منتخب کریں" },
  "voucher.transfer": { en: "Transfer (Cash ↔ Bank)", ur: "منتقلی (نقد ↔ بینک)" },
  "voucher.transfers": { en: "Transfers", ur: "منتقلیاں" },
  "voucher.vouchers": { en: "Vouchers", ur: "واؤچرز" },
  "voucher.fromAccount": { en: "From", ur: "سے" },
  "voucher.toAccount": { en: "To", ur: "کو" },
  "voucher.selectAccount": { en: "Select account", ur: "اکاؤنٹ منتخب کریں" },
  "voucher.fromRequired": { en: "Please select a source account", ur: "براہ کرم ذریعہ اکاؤنٹ منتخب کریں" },
  "voucher.toRequired": { en: "Please select a destination account", ur: "براہ کرم منزل اکاؤنٹ منتخب کریں" },
  "voucher.sameAccountError": { en: "Source and destination must be different", ur: "ذریعہ اور منزل مختلف ہونے چاہئیں" },
  "voucher.details": { en: "Voucher Details", ur: "واؤچر کی تفصیلات" },
  "invoice.details": { en: "Invoice Details", ur: "انوائس کی تفصیلات" },
  "common.saving": { en: "Saving...", ur: "محفوظ ہو رہا ہے..." },

  // Dashboard drill-down
  "dashboard.viewTransactions": { en: "View Transactions", ur: "لین دین دیکھیں" },
  "dashboard.runningBalance": { en: "Balance", ur: "بیلنس" },
  "dashboard.topSuppliers": { en: "Top Suppliers", ur: "اہم فراہم کنندگان" },
  "dashboard.outstandingInvoices": { en: "Outstanding Invoices", ur: "بقایا انوائسز" },
  "dashboard.voucherNo": { en: "Voucher #", ur: "واؤچر نمبر" },
  "dashboard.invoiceNo": { en: "Invoice #", ur: "انوائس نمبر" },
  "dashboard.contact": { en: "Contact", ur: "رابطہ" },
  "dashboard.date": { en: "Date", ur: "تاریخ" },
  "dashboard.amount": { en: "Amount", ur: "رقم" },
  "dashboard.expense": { en: "Expense", ur: "خرچہ" },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem("lang") as Language) || "en";
  });

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => {
      const next = prev === "en" ? "ur" : "en";
      localStorage.setItem("lang", next);
      return next;
    });
  }, []);

  const t = useCallback(
    (key: string) => translations[key]?.[language] ?? key,
    [language]
  );

  const isRtl = language === "ur";

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRtl }}>
      <div dir={isRtl ? "rtl" : "ltr"} className={isRtl ? "font-urdu" : ""}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
